function S = buildHUDandControls(S)
%RET.BUILDHUDandCONTROLS Build UI panels + controls; callbacks point to +ret

fig = S.fig;

fontsize1 = 10;
fontsize2 = 9;
fontsize3 = 8;
fontsize4 = 8;

%% =========================
% Main container panel
% =========================
S.hud = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0.01 0.02 0.52 0.96], ...
    'Title', 'Retention Ring Calculator', ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0]);

%% =========================
% Inputs panel
% =========================
S.pIn = uipanel(S.hud, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.52 0.47 0.46], ...
    'Title', 'Inputs', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

%% =========================
% Outputs container
% =========================
S.pOut = uipanel(S.hud, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.47 0.48], ...
    'Title', 'Outputs', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

% Geometry outputs subpanel
S.pOutGeom = uipanel(S.pOut, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.47 0.96], ...
    'Title', 'Geometry', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

S.txtGeom = uicontrol(S.pOutGeom, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.96 0.96], ...
    'String', '', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize2);

% Force / Stress outputs subpanel
S.pOutStress = uipanel(S.pOut, ...
    'Units', 'normalized', ...
    'Position', [0.51 0.02 0.47 0.96], ...
    'Title', 'Force / Stress', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

S.txtStress = uicontrol(S.pOutStress, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.96 0.96], ...
    'String', '', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize2);

%% =========================
% Optimization panel
% =========================
S.pOpt = uipanel(S.hud, ...
    'Units', 'normalized', ...
    'Position', [0.51 0.02 0.47 0.96], ...
    'Title', 'Optimization & Constraints', ...
    'ForegroundColor', [0 0 0.6], ...
    'BackgroundColor', [0.95 0.95 1]);

%% =========================
% Allowables (green)
% =========================
S.pOptAllow = uipanel(S.pOpt, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.64 0.96 0.34], ...
    'Title', 'Allowables (KSI)', ...
    'ForegroundColor', [0 0.4 0], ...
    'BackgroundColor', [0.9 1 0.9]);

% Ensure structs exist
if ~isfield(S,'allow') || ~isstruct(S.allow), S.allow = struct(); end
if ~isfield(S.allow,'yield') || ~isstruct(S.allow.yield), S.allow.yield = struct(); end
if ~isfield(S.allow,'ult')   || ~isstruct(S.allow.ult),   S.allow.ult   = struct(); end

% ===== Defaults (sourced from ret.defaults) =====
D = ret.defaults();

S.allow.yield.shearOut       = localDefField(S.allow.yield, 'shearOut',       D.allow.yield.shearOut);
S.allow.ult.shearOut         = localDefField(S.allow.ult,   'shearOut',       D.allow.ult.shearOut);

S.allow.yield.netTension     = localDefField(S.allow.yield, 'netTension',     D.allow.yield.netTension);
S.allow.ult.netTension       = localDefField(S.allow.ult,   'netTension',     D.allow.ult.netTension);

S.allow.yield.pressureVessel = localDefField(S.allow.yield, 'pressureVessel', D.allow.yield.pressureVessel);
S.allow.ult.pressureVessel   = localDefField(S.allow.ult,   'pressureVessel', D.allow.ult.pressureVessel);

S.allow.yield.bearing        = localDefField(S.allow.yield, 'bearing',        D.allow.yield.bearing);
S.allow.ult.bearing          = localDefField(S.allow.ult,   'bearing',        D.allow.ult.bearing);

% Pins
S.allow.yield.pinShear       = localDefField(S.allow.yield, 'pinShear', D.allow.yield.pinShear);
S.allow.ult.pinShear         = localDefField(S.allow.ult,   'pinShear', D.allow.ult.pinShear);

% Ret ring
S.allow.yield.ret_shearOut   = localDefField(S.allow.yield, 'ret_shearOut',   D.allow.yield.ret_shearOut);
S.allow.ult.ret_shearOut     = localDefField(S.allow.ult,   'ret_shearOut',   D.allow.ult.ret_shearOut);
S.allow.yield.ret_netTension = localDefField(S.allow.yield, 'ret_netTension', D.allow.yield.ret_netTension);
S.allow.ult.ret_netTension   = localDefField(S.allow.ult,   'ret_netTension', D.allow.ult.ret_netTension);
S.allow.yield.ret_bearing    = localDefField(S.allow.yield, 'ret_bearing',    D.allow.yield.ret_bearing);
S.allow.ult.ret_bearing      = localDefField(S.allow.ult,   'ret_bearing',    D.allow.ult.ret_bearing);

% Column layout: Label | Yield | Ultimate
xL  = 0.02; wL  = 0.52;
xY  = 0.56; wY  = 0.19;
xU  = 0.78; wU  = 0.19;

% For casing allowables we use a single wide box (applies to both yield + ultimate)
xC  = xY;
wC  = (xU + wU) - xY;

hA  = 0.095;

% Start the rows a bit lower so the header text never gets clipped
% by the top edge of the allowables panel.
yA0 = 0.80;
dyA = 0.105;

% Header row (above the first allowable row)
% Keep yHdr + hHdr <= 0.99 to avoid top clipping.
yHdr = min(0.93, yA0 + 1.1*dyA);
hHdr = 0.06;


uicontrol(S.pOptAllow,'Style','text','Units','normalized', ...
    'Position',[xL yHdr wL hHdr],'String','Failure Mode', ...
    'HorizontalAlignment','left','BackgroundColor',[0.9 1 0.9], ...
    'ForegroundColor',[0 0.4 0],'FontName','Consolas','FontSize',fontsize4,'FontWeight','bold');

uicontrol(S.pOptAllow,'Style','text','Units','normalized', ...
    'Position',[xY yHdr wY hHdr],'String','Yield', ...
    'HorizontalAlignment','center','BackgroundColor',[0.9 1 0.9], ...
    'ForegroundColor',[0 0.4 0],'FontName','Consolas','FontSize',fontsize4,'FontWeight','bold');

uicontrol(S.pOptAllow,'Style','text','Units','normalized', ...
    'Position',[xU yHdr wU hHdr],'String','Ultimate', ...
    'HorizontalAlignment','center','BackgroundColor',[0.9 1 0.9], ...
    'ForegroundColor',[0 0.4 0],'FontName','Consolas','FontSize',fontsize4,'FontWeight','bold');

mkLabelA = @(txt, yy) uicontrol(S.pOptAllow,'Style','text','Units','normalized', ...
    'Position',[xL yy wL hA],'String',txt,'HorizontalAlignment','left', ...
    'BackgroundColor',[0.9 1 0.9],'ForegroundColor',[0 0 0], ...
    'FontName','Consolas','FontSize',fontsize4);

mkEditA = @(val, yy, xpos, tag) uicontrol(S.pOptAllow,'Style','edit','Units','normalized', ...
    'Position',[xpos yy wY hA], ...
    'String', localNumStr(val,'%.4f'), ...
    'Tag',tag, ...
    'BackgroundColor',[1 1 1],'ForegroundColor',[0 0 0],'FontSize',fontsize3, ...
    'Callback',@ret.onAllowablesChanged);

mkEditWideA = @(val, yy, tag) uicontrol(S.pOptAllow,'Style','edit','Units','normalized', ...
    'Position',[xC yy wC hA], ...
    'String', localNumStr(val,'%.4f'), ...
    'Tag',tag, ...
    'BackgroundColor',[1 1 1],'ForegroundColor',[0 0 0],'FontSize',fontsize3, ...
    'Callback',@ret.onAllowablesChanged);

% Rows
yy = yA0;
mkLabelA('Casing Shear-Out', yy);
S.edAllowC_shearOut = mkEditWideA(S.allow.yield.shearOut, yy, 'allow_c_shearOut');

yy = yy - dyA;
mkLabelA('Casing Net Tension', yy);
S.edAllowC_netT = mkEditWideA(S.allow.yield.netTension, yy, 'allow_c_netTension');

yy = yy - dyA;
mkLabelA('Casing Bearing', yy);
S.edAllowC_bear = mkEditWideA(S.allow.yield.bearing, yy, 'allow_c_bearing');

yy = yy - dyA;
mkLabelA('Casing Pressure Vessel', yy);
S.edAllowC_pv = mkEditWideA(S.allow.yield.pressureVessel, yy, 'allow_c_pressureVessel');

yy = yy - dyA;
mkLabelA('Pins Pin Shear', yy);
S.edAllowY_ps = mkEditA(S.allow.yield.pinShear, yy, xY, 'allow_y_pinShear');
S.edAllowU_ps = mkEditA(S.allow.ult.pinShear,   yy, xU, 'allow_u_pinShear');

yy = yy - dyA;
mkLabelA('Ret Ring Shear-Out', yy);
S.edAllowY_retSO = mkEditA(S.allow.yield.ret_shearOut, yy, xY, 'allow_y_ret_shearOut');
S.edAllowU_retSO = mkEditA(S.allow.ult.ret_shearOut,   yy, xU, 'allow_u_ret_shearOut');

yy = yy - dyA;
mkLabelA('Ret Ring Net Tension', yy);
S.edAllowY_retNT = mkEditA(S.allow.yield.ret_netTension, yy, xY, 'allow_y_ret_netTension');
S.edAllowU_retNT = mkEditA(S.allow.ult.ret_netTension,   yy, xU, 'allow_u_ret_netTension');

yy = yy - dyA;
mkLabelA('Ret Ring Bearing', yy);
S.edAllowY_retB = mkEditA(S.allow.yield.ret_bearing, yy, xY, 'allow_y_ret_bearing');
S.edAllowU_retB = mkEditA(S.allow.ult.ret_bearing,   yy, xU, 'allow_u_ret_bearing');

%% =========================
% Optimization Bounds (purple) - Min Pitch UI removed
% =========================
S.pOptBounds = uipanel(S.pOpt, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.40 0.96 0.22], ...
    'Title', 'Optimization Bounds [min, max]', ...
    'ForegroundColor', [0.4 0 0.4], ...
    'BackgroundColor', [1 0.95 1]);

yB  = 0.82;
dyB = 0.16;
xLB = 0.02; wLB = 0.38;
xMinB = 0.42; wMinB = 0.27;
xMaxB = 0.71; wMaxB = 0.27;
hB  = 0.14;

mkLabelB = @(txt, yy2) uicontrol(S.pOptBounds, 'Style','text', 'Units','normalized', ...
    'Position',[xLB yy2 wLB hB], 'String',txt, 'HorizontalAlignment','left', ...
    'BackgroundColor',[1 0.95 1], 'ForegroundColor',[0 0 0], 'FontName','Consolas', 'FontSize', fontsize4);

mkEditB = @(val, yy2, xpos) uicontrol(S.pOptBounds, 'Style','edit', 'Units','normalized', ...
    'Position',[xpos yy2 wMinB hB], 'String',num2str(val, '%.3f'), ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], 'FontSize', fontsize3, ...
    'Callback',@ret.onBoundsChanged);

uicontrol(S.pOptBounds, 'Style','text', 'Units','normalized', ...
    'Position',[xMinB yB+dyB*0.28 wMinB hB*0.65], 'String','Min', 'HorizontalAlignment','center', ...
    'BackgroundColor',[1 0.95 1], 'ForegroundColor',[0.3 0 0.3], 'FontName','Consolas', 'FontSize', fontsize4, 'FontWeight','bold');

uicontrol(S.pOptBounds, 'Style','text', 'Units','normalized', ...
    'Position',[xMaxB yB+dyB*0.28 wMaxB hB*0.65], 'String','Max', 'HorizontalAlignment','center', ...
    'BackgroundColor',[1 0.95 1], 'ForegroundColor',[0.3 0 0.3], 'FontName','Consolas', 'FontSize', fontsize4, 'FontWeight','bold');

mkLabelB('Wall Thick (in)', yB);
S.edBndTmin = mkEditB(S.optBounds.t(1), yB, xMinB);
S.edBndTmax = mkEditB(S.optBounds.t(2), yB, xMaxB);

mkLabelB('Axial Rows', yB-dyB);
S.edBndRowsMin = mkEditB(S.optBounds.nRows(1), yB-dyB, xMinB);
S.edBndRowsMax = mkEditB(S.optBounds.nRows(2), yB-dyB, xMaxB);

mkLabelB('Pins/Row', yB-2*dyB);
S.edBndPPRmin = mkEditB(S.optBounds.nPinsPerRow(1), yB-2*dyB, xMinB);
S.edBndPPRmax = mkEditB(S.optBounds.nPinsPerRow(2), yB-2*dyB, xMaxB);

mkLabelB('Row Space (in)', yB-3*dyB);
S.edBndRowSpMin = mkEditB(S.optBounds.rowSpacing(1), yB-3*dyB, xMinB);
S.edBndRowSpMax = mkEditB(S.optBounds.rowSpacing(2), yB-3*dyB, xMaxB);

mkLabelB('1st Row Ofs (in)', yB-4*dyB);
S.edBndFirstMin = mkEditB(S.optBounds.firstRowZ(1), yB-4*dyB, xMinB);
S.edBndFirstMax = mkEditB(S.optBounds.firstRowZ(2), yB-4*dyB, xMaxB);

mkLabelB('Pin Dia (in)', yB-5*dyB);
S.edBndPinDiaMin = mkEditB(S.optBounds.pinDia(1), yB-5*dyB, xMinB);
S.edBndPinDiaMax = mkEditB(S.optBounds.pinDia(2), yB-5*dyB, xMaxB);

%% =========================
% Margin Status grid
% =========================
S.pOptResults = uipanel(S.pOpt, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.11 0.96 0.28], ...
    'Title', 'Margin Status', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

S.marginN = 8;

x1 = 0.02; w1 = 0.22;
x2 = 0.25; w2 = 0.35;
x3 = 0.61; w3 = 0.18;
x4 = 0.80; w4 = 0.18;

hR = 0.10;
y0 = 0.88;

uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
    'Position',[x1 y0 w1 hR],'String','Component', ...
    'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4,'FontWeight','bold');
uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
    'Position',[x2 y0 w2 hR],'String','Load Case', ...
    'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4,'FontWeight','bold');
uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
    'Position',[x3 y0 w3 hR],'String','Yield MOS', ...
    'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4,'FontWeight','bold');
uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
    'Position',[x4 y0 w4 hR],'String','Ultimate MOS', ...
    'HorizontalAlignment','left','BackgroundColor',[1 1 1], ...
    'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4,'FontWeight','bold');

S.marginCells = gobjects(S.marginN,4);
for r = 1:S.marginN
    yy2 = y0 - r*hR;

    S.marginCells(r,1) = uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
        'Position',[x1 yy2 w1 hR],'String','', 'HorizontalAlignment','left', ...
        'BackgroundColor',[1 1 1],'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4);

    S.marginCells(r,2) = uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
        'Position',[x2 yy2 w2 hR],'String','', 'HorizontalAlignment','left', ...
        'BackgroundColor',[1 1 1],'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4);

    S.marginCells(r,3) = uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
        'Position',[x3 yy2 w3 hR],'String','', 'HorizontalAlignment','left', ...
        'BackgroundColor',[1 1 1],'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4);

    S.marginCells(r,4) = uicontrol(S.pOptResults,'Style','text','Units','normalized', ...
        'Position',[x4 yy2 w4 hR],'String','', 'HorizontalAlignment','left', ...
        'BackgroundColor',[1 1 1],'ForegroundColor',[0 0 0],'FontName','Consolas','FontSize',fontsize4);
end

%% =========================
% Optimize button + status
% =========================
S.btnOptimize = uicontrol(S.pOpt, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.12 0.02 0.76 0.06], ...
    'String', 'Run Optimization', ...
    'BackgroundColor', [0.2 0.6 0.2], ...
    'ForegroundColor', [1 1 1], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize1, ...
    'FontWeight', 'bold', ...
    'Callback', @ret.onOptimizeClicked);

S.txtOptStatus = uicontrol(S.pOpt, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.08 0.96 0.02], ...
    'String', '', ...
    'HorizontalAlignment', 'center', ...
    'BackgroundColor', [0.95 0.95 1], ...
    'ForegroundColor', [0 0 0.6], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize3);

%% =========================
% Inputs panel controls (same as your latest layout)
% =========================
yTop = 0.92;
dy   = 0.062;
xL2  = 0.04; wL2 = 0.52;
xC2  = 0.58; wC2 = 0.38;
h2   = 0.060;

mkLabel = @(txt, yy3) uicontrol(S.pIn, 'Style','text', 'Units','normalized', ...
    'Position',[xL2 yy3 wL2 h2], 'String',txt, 'HorizontalAlignment','left', ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], 'FontName','Consolas', 'FontSize', fontsize2);

mkEdit = @(val, yy3, tag) uicontrol(S.pIn, 'Style','edit', 'Units','normalized', ...
    'Position',[xC2 yy3 wC2 h2], 'String',num2str(val), 'Tag',tag, ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], ...
    'Callback',@ret.onAnyInputChanged);

mainYellow = [1 1 0.6];

mkLabel('Inner Diameter (in)', yTop);
S.edID = mkEdit(S.ID, yTop, 'ID');

mkLabel('Wall Thickness (in)', yTop-dy);
S.edT = mkEdit(S.t, yTop-dy, 't');
set(S.edT, 'BackgroundColor', mainYellow);

mkLabel('MEOP (psi)', yTop-2*dy);
S.edMEOP = mkEdit(S.MEOP_psi, yTop-2*dy, 'MEOP_psi');

% Ensure FOS defaults exist
% - Casing uses a single FOS
% - Pins and retention ring share the same Yield/Ultimate FOS inputs
if ~isfield(S,'FOS') || ~isstruct(S.FOS), S.FOS = struct(); end
if ~isfield(S.FOS,'casing')  || ~isfinite(S.FOS.casing),  S.FOS.casing  = 2.00; end
if ~isfield(S.FOS,'comp_y')  || ~isfinite(S.FOS.comp_y),  S.FOS.comp_y  = 1.75; end
if ~isfield(S.FOS,'comp_u')  || ~isfinite(S.FOS.comp_u),  S.FOS.comp_u  = 2.00; end

mkLabel('Casing FOS', yTop-3*dy);
S.edFOS_casing = mkEdit(S.FOS.casing, yTop-3*dy, 'FOS.casing');

mkLabel('Pin/Ret Ring Yield FOS', yTop-4*dy);
S.edFOS_compY = mkEdit(S.FOS.comp_y, yTop-4*dy, 'FOS.comp_y');

mkLabel('Pin/Ret Ring Ultimate FOS', yTop-5*dy);
S.edFOS_compU = mkEdit(S.FOS.comp_u, yTop-5*dy, 'FOS.comp_u');

mkLabel('Axial Rows', yTop-6*dy);
S.edRows = mkEdit(S.nRows, yTop-6*dy, 'nRows');
set(S.edRows, 'BackgroundColor', mainYellow);

mkLabel('Pins per Row', yTop-7*dy);
S.edPPR = mkEdit(S.nPinsPerRow, yTop-7*dy, 'nPinsPerRow');
set(S.edPPR, 'BackgroundColor', mainYellow);

mkLabel('Row Spacing (in)', yTop-8*dy);
S.edRowSp = mkEdit(S.rowSpacing, yTop-8*dy, 'rowSpacing');
set(S.edRowSp, 'BackgroundColor', mainYellow);

mkLabel('First Row Offset (in)', yTop-9*dy);
S.edFirst = mkEdit(S.firstRowZ, yTop-9*dy, 'firstRowZ');
set(S.edFirst, 'BackgroundColor', mainYellow);

mkLabel('Pin Diameter (in)', yTop-10*dy);
pinStrs = compose('%.4f', S.allowedPinDias);
[~, idx] = min(abs(S.allowedPinDias - S.pinDia));

S.ddPinDia = uicontrol(S.pIn, ...
    'Style','popupmenu', ...
    'Units','normalized', ...
    'Position',[xC2 (yTop-10*dy) wC2 h2], ...
    'String', pinStrs, ...
    'Value', idx, ...
    'BackgroundColor', mainYellow, ...
    'FontName','Consolas', ...
    'FontSize', 8, ...
    'Callback',@ret.onAnyInputChanged);
set(S.ddPinDia, 'ForegroundColor', [0 0 0]);

mkLabel('Pin Pattern*', yTop-11*dy);
isAlt = (S.pinPatternMode == "alternating");
btnStr2 = "Spiral";
if isAlt, btnStr2 = "Alternating"; end

S.btnPattern = uicontrol(S.pIn, 'Style','togglebutton', 'Units','normalized', ...
    'Position',[xC2 (yTop-11*dy) wC2 h2], ...
    'String', btnStr2, ...
    'Value', isAlt, ...
    'BackgroundColor',[0.95 0.95 0.95], ...
    'ForegroundColor',[0 0 0], ...
    'FontName','Consolas', ...
    'FontSize', fontsize3, ...
    'Callback',@ret.onAnyInputChanged);

% -------- View toggle + Ret ring visibility (grouped with pattern) --------
mkLabel('View Toggle', yTop-12*dy);
isFull = isfield(S,'lengthMode') && (S.lengthMode == "full");
btnStr = 'Retention Detail View';
if isFull, btnStr = 'Full Casing'; end
S.btnLengthMode = uicontrol(S.pIn, 'Style','togglebutton', 'Units','normalized', ...
    'Position',[xC2 (yTop-12*dy) wC2 h2], ...
    'String', btnStr, ...
    'Value', double(isFull), ...
    'BackgroundColor',[0.95 0.95 0.95], ...
    'ForegroundColor',[0 0 0], ...
    'FontName','Consolas', ...
    'FontSize', fontsize2, ...
    'Callback',@ret.onAnyInputChanged);

% Default if missing
if ~isfield(S,'showRetRings') || ~islogical(S.showRetRings)
    S.showRetRings = true;
end
mkLabel('Ret Ring', yTop-13*dy);
isShown = (S.showRetRings == true);
btnRetStr = 'Visible';
if ~isShown, btnRetStr = 'Hidden'; end
S.btnShowRetRings = uicontrol(S.pIn, 'Style','togglebutton', 'Units','normalized', ...
    'Position',[xC2 (yTop-13*dy) wC2 h2], ...
    'String', btnRetStr, ...
    'Value', double(isShown), ...
    'BackgroundColor',[0.95 0.95 0.95], ...
    'ForegroundColor',[0 0 0], ...
    'FontName','Consolas', ...
    'FontSize', fontsize2, ...
    'Callback',@ret.onAnyInputChanged);

%% =========================
% Local helpers
% =========================
    function s = localNumStr(v, fmt) %#ok<INUSD>
        % Smart formatting for UI fields:
        % - NaN -> blank
        % - integers -> no trailing decimals
        % - otherwise -> trimmed decimals
        if ~isfinite(v)
            s = '';
            return;
        end
        if abs(v - round(v)) < 1e-9
            s = sprintf('%d', round(v));
        else
            % keep up to 4 decimals but strip trailing zeros
            s = sprintf('%.4f', v);
            s = regexprep(s, '(?<=\d)0+$', '');
            s = regexprep(s, '\.$', '');
        end
    end

    function v = localDefField(st, field, defaultVal)
        if isfield(st, field) && isfinite(st.(field))
            v = st.(field);
        else
            v = defaultVal;
        end
    end

end