function S = buildHUDandControls(S)
%RET.BUILDHUDandCONTROLS Build UI panels + controls; callbacks point to +ret

fig = S.fig;

fontsize1 = 10;
fontsize2 = 9;
fontsize3 = 8;
fontsize4 = 8;

% Main container panel
S.hud = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0.01 0.02 0.52 0.96], ...
    'Title', 'Retention Ring Calculator', ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0]);

% Inputs panel
S.pIn = uipanel(S.hud, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.52 0.47 0.46], ...
    'Title', 'Inputs', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

% Outputs container
S.pOut = uipanel(S.hud, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.47 0.48], ...
    'Title', 'Outputs', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

% Geometry outputs subpanel
S.pOutGeom = uipanel(S.pOut, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.47 0.96], ...
    'Title', 'Geometry', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

S.txtGeom = uicontrol(S.pOutGeom, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.96 0.96], ...
    'String', '', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize2);

% Force / Stress outputs subpanel
S.pOutStress = uipanel(S.pOut, ...
    'Units', 'normalized', ...
    'Position', [0.51 0.02 0.47 0.96], ...
    'Title', 'Force / Stress', ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

S.txtStress = uicontrol(S.pOutStress, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.96 0.96], ...
    'String', '', ...
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor', [0 0 0], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize2);

% Optimization panel
S.pOpt = uipanel(S.hud, ...
    'Units', 'normalized', ...
    'Position', [0.51 0.02 0.47 0.96], ...
    'Title', 'Optimization & Constraints', ...
    'ForegroundColor', [0 0 0.6], ...
    'BackgroundColor', [0.95 0.95 1]);

% ----- Target Constraints (green) -----
S.pOptTargets = uipanel(S.pOpt, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.66 0.96 0.32], ...   % slightly shorter
    'Title', 'Target Constraints', ...
    'ForegroundColor', [0 0.4 0], ...
    'BackgroundColor', [0.9 1 0.9]);

yT = 0.86; dyT = 0.12;
xLT = 0.02; wLT = 0.55;
xCT = 0.58; wCT = 0.40;
hT = 0.10;

mkLabelT = @(txt, yy) uicontrol(S.pOptTargets, 'Style','text', 'Units','normalized', ...
    'Position',[xLT yy wLT hT], 'String',txt, 'HorizontalAlignment','left', ...
    'BackgroundColor',[0.9 1 0.9], 'ForegroundColor',[0 0 0], 'FontName','Consolas', 'FontSize', fontsize4);

mkEditT = @(val, yy, fmt) uicontrol(S.pOptTargets, 'Style','edit', 'Units','normalized', ...
    'Position',[xCT yy wCT hT], 'String',num2str(val, fmt), ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], 'FontSize', fontsize3, ...
    'Callback',@ret.onConstraintChanged);

mkLabelT('Shear Out (KSI)', yT);         S.edTgtShearOut = mkEditT(S.targets.shearOut_max, yT, '%.4f');
mkLabelT('Net Tension (KSI)', yT-dyT);   S.edTgtNetTens  = mkEditT(S.targets.netTension_max, yT-dyT, '%.4f');
mkLabelT('Pin Shear (KSI)', yT-2*dyT);   S.edTgtPinShear = mkEditT(S.targets.pinShear_max, yT-2*dyT, '%.4f');
mkLabelT('Bearing (KSI)', yT-3*dyT);     S.edTgtBearing  = mkEditT(S.targets.bearing_max, yT-3*dyT, '%.4f');
mkLabelT('Hoop (KSI)', yT-4*dyT);        S.edTgtHoop     = mkEditT(S.targets.hoop_max, yT-4*dyT, '%.4f');
mkLabelT('Axial (KSI)', yT-5*dyT);       S.edTgtAxial    = mkEditT(S.targets.axial_max, yT-5*dyT, '%.4f');
mkLabelT('Pin Shear FOS Min', yT-6*dyT);       S.edTgtFOS      = mkEditT(S.targets.pinShearFOS_min, yT-6*dyT, '%.4f');

% ----- Optimization Bounds (purple) -----
S.pOptBounds = uipanel(S.pOpt, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.34 0.96 0.30], ...   % slightly taller than before
    'Title', 'Optimization Bounds [min, max]', ...
    'ForegroundColor', [0.4 0 0.4], ...
    'BackgroundColor', [1 0.95 1]);

yB  = 0.86;
dyB = 0.12;
xLB = 0.02; wLB = 0.38;
xMinB = 0.42; wMinB = 0.27;
xMaxB = 0.71; wMaxB = 0.27;
hB  = 0.11;

mkLabelB = @(txt, yy) uicontrol(S.pOptBounds, 'Style','text', 'Units','normalized', ...
    'Position',[xLB yy wLB hB], 'String',txt, 'HorizontalAlignment','left', ...
    'BackgroundColor',[1 0.95 1], 'ForegroundColor',[0 0 0], 'FontName','Consolas', 'FontSize', fontsize4);

mkEditB = @(val, yy, xpos) uicontrol(S.pOptBounds, 'Style','edit', 'Units','normalized', ...
    'Position',[xpos yy wMinB hB], 'String',num2str(val, '%.3f'), ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], 'FontSize', fontsize3, ...
    'Callback',@ret.onBoundsChanged);

uicontrol(S.pOptBounds, 'Style','text', 'Units','normalized', ...
    'Position',[xMinB yB+dyB*0.3 wMinB hB*0.7], 'String','Min', 'HorizontalAlignment','center', ...
    'BackgroundColor',[1 0.95 1], 'ForegroundColor',[0.3 0 0.3], 'FontName','Consolas', 'FontSize', fontsize4, 'FontWeight','bold');

uicontrol(S.pOptBounds, 'Style','text', 'Units','normalized', ...
    'Position',[xMaxB yB+dyB*0.3 wMaxB hB*0.7], 'String','Max', 'HorizontalAlignment','center', ...
    'BackgroundColor',[1 0.95 1], 'ForegroundColor',[0.3 0 0.3], 'FontName','Consolas', 'FontSize', fontsize4, 'FontWeight','bold');

mkLabelB('Wall Thick (in)', yB);
S.edBndTmin = mkEditB(S.optBounds.t(1), yB, xMinB);
S.edBndTmax = mkEditB(S.optBounds.t(2), yB, xMaxB);

mkLabelB('Axial Rows', yB-dyB);
S.edBndRowsMin = mkEditB(S.optBounds.nRows(1), yB-dyB, xMinB);
S.edBndRowsMax = mkEditB(S.optBounds.nRows(2), yB-dyB, xMaxB);

mkLabelB('Pins/Row', yB-2*dyB);
S.edBndPPRmin = mkEditB(S.optBounds.nPinsPerRow(1), yB-2*dyB, xMinB);
S.edBndPPRmax = mkEditB(S.optBounds.nPinsPerRow(2), yB-2*dyB, xMaxB);

mkLabelB('Row Space (in)', yB-3*dyB);
S.edBndRowSpMin = mkEditB(S.optBounds.rowSpacing(1), yB-3*dyB, xMinB);
S.edBndRowSpMax = mkEditB(S.optBounds.rowSpacing(2), yB-3*dyB, xMaxB);

mkLabelB('1st Row Ofs (in)', yB-4*dyB);
S.edBndFirstMin = mkEditB(S.optBounds.firstRowZ(1), yB-4*dyB, xMinB);
S.edBndFirstMax = mkEditB(S.optBounds.firstRowZ(2), yB-4*dyB, xMaxB);

mkLabelB('Pin Dia (in)', yB-5*dyB);
S.edBndPinDiaMin = mkEditB(S.optBounds.pinDia(1), yB-5*dyB, xMinB);
S.edBndPinDiaMax = mkEditB(S.optBounds.pinDia(2), yB-5*dyB, xMaxB);

mkLabelB('Min Pitch (x dia)', yB-6*dyB);
S.edMinCircPitch = uicontrol(S.pOptBounds, 'Style','edit', 'Units','normalized', ...
    'Position',[xMinB yB-6*dyB wMinB+wMaxB+0.02 hB], 'String',num2str(S.minCircPitchFactor, '%.1f'), ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], 'FontSize', fontsize3, ...
    'Callback',@ret.onBoundsChanged);

marginFrac = S.marginFrac;  % 5% buffer

% ----- Constraint Status (results) -----
S.pOptResults = uipanel(S.pOpt, ...
    'Units', 'normalized', ...
    'Position', [0.02 0.13 0.96 0.19], ...
    'Title', sprintf('Constraint Status (%.0f%% buffer)', marginFrac*100), ...
    'ForegroundColor', [0 0 0], ...
    'BackgroundColor', [1 1 1]);

% One line per constraint + one banner line (no HTML)
S.txtOptLines = gobjects(8,1);
lineH = 0.115;
topY  = 0.86;

for k = 1:8
    yy = topY - (k-1)*lineH;
    S.txtOptLines(k) = uicontrol(S.pOptResults, 'Style','text', 'Units','normalized', ...
        'Position',[0.02 yy 0.96 lineH-0.01], 'String','', ...
        'HorizontalAlignment','left', 'BackgroundColor',[1 1 1], ...
        'ForegroundColor',[0 0 0], 'FontName','Consolas', 'FontSize', fontsize4);
end

set(S.txtOptLines(1), 'String', 'Adjust constraints/bounds, then Run Optimization');

% Button + status line
S.btnOptimize = uicontrol(S.pOpt, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'Position', [0.1 0.02 0.8 0.08], ...
    'String', 'Run Optimization', ...
    'BackgroundColor', [0.2 0.6 0.2], ...
    'ForegroundColor', [1 1 1], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize1, ...
    'FontWeight', 'bold', ...
    'Callback', @ret.onOptimizeClicked);

S.txtOptStatus = uicontrol(S.pOpt, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.10 0.96 0.02], ...
    'String', '', ...
    'HorizontalAlignment', 'center', ...
    'BackgroundColor', [0.95 0.95 1], ...
    'ForegroundColor', [0 0 0.6], ...
    'FontName', 'Consolas', ...
    'FontSize', fontsize3);

%% ---- Inputs panel controls ----
yTop = 0.90; dy = 0.075;
xL  = 0.04; wL = 0.52;
xC  = 0.58; wC = 0.38;
h   = 0.07;

mkLabel = @(txt, yy) uicontrol(S.pIn, 'Style','text', 'Units','normalized', ...
    'Position',[xL yy wL h], 'String',txt, 'HorizontalAlignment','left', ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], 'FontName','Consolas', 'FontSize', fontsize2);

mkEdit = @(val, yy, tag) uicontrol(S.pIn, 'Style','edit', 'Units','normalized', ...
    'Position',[xC yy wC h], 'String',num2str(val), 'Tag',tag, ...
    'BackgroundColor',[1 1 1], 'ForegroundColor',[0 0 0], ...
    'Callback',@ret.onAnyInputChanged);

mkLabel('Inner Diameter (in)', yTop);                  S.edID      = mkEdit(S.ID,         yTop,        'ID');

mainYellow = [1 1 0.6];  % highlight for primary design inputs

mkLabel('Wall Thickness (in)', yTop-dy);               S.edT       = mkEdit(S.t,          yTop-dy,     't');
set(S.edT, 'BackgroundColor', mainYellow);

mkLabel('Modeled Length', yTop-2*dy);
isFull = (isfield(S,'lengthMode') && S.lengthMode == "full");
lenStr = "Length: 10 in (aft only)";
if isFull, lenStr = "Length: 96 in (both ends)"; end
S.btnLengthMode = uicontrol(S.pIn, 'Style','togglebutton', 'Units','normalized', ...
    'Position',[xC (yTop-2*dy) wC h], ...
    'String', lenStr, ...
    'Value', double(isFull), ...
    'BackgroundColor',[0.95 0.95 0.95], ...
    'ForegroundColor',[0 0 0], ...
    'FontName','Consolas', ...
    'FontSize', fontsize2, ...
    'Callback',@ret.onAnyInputChanged);

mkLabel('MEOP (psi)', yTop-3*dy);                      S.edMEOP    = mkEdit(S.MEOP_psi,   yTop-3*dy,   'MEOP_psi');
mkLabel('Casing Design Factor (xMEOP)', yTop-4*dy);           S.edDF      = mkEdit(S.DF,         yTop-4*dy,   'DF');

mkLabel('Axial Rows', yTop-5*dy);                      S.edRows    = mkEdit(S.nRows,      yTop-5*dy,   'nRows');
set(S.edRows, 'BackgroundColor', mainYellow);

mkLabel('Pins per Row', yTop-6*dy);                    S.edPPR     = mkEdit(S.nPinsPerRow,yTop-6*dy,   'nPinsPerRow');
set(S.edPPR, 'BackgroundColor', mainYellow);

mkLabel('Row Spacing (in)', yTop-7*dy);                S.edRowSp   = mkEdit(S.rowSpacing, yTop-7*dy,   'rowSpacing');
set(S.edRowSp, 'BackgroundColor', mainYellow);

mkLabel('First Row Offset (in)', yTop-8*dy);           S.edFirst   = mkEdit(S.firstRowZ,  yTop-8*dy,   'firstRowZ');
set(S.edFirst, 'BackgroundColor', mainYellow);

mkLabel('Pin Diameter (in)', yTop-9*dy);

pinStrs = compose('%.4f', S.allowedPinDias);
[~, idx] = min(abs(S.allowedPinDias - S.pinDia)); % nearest match

S.ddPinDia = uicontrol(S.pIn, ...
    'Style','popupmenu', ...
    'Units','normalized', ...
    'Position',[xC (yTop-9*dy) wC h], ...
    'String', pinStrs, ...
    'Value', idx, ...
    'BackgroundColor', mainYellow, ...
    'FontName','Consolas', ...
    'FontSize',8, ...
    'Callback',@ret.onAnyInputChanged);

set(S.ddPinDia,'ForegroundColor',[0 0 0]);

mkLabel('Pin Pattern*', yTop-10*dy);
isAlt = (S.pinPatternMode == "alternating");
btnStr = "Pattern: Progressive";
if isAlt, btnStr = "Pattern: Alternating"; end
S.btnPattern = uicontrol(S.pIn, 'Style','togglebutton', 'Units','normalized', ...
    'Position',[xC (yTop-10*dy) wC h], ...
    'String', btnStr, ...
    'Value', isAlt, ...
    'BackgroundColor', [1 1 1], ...
    'ForegroundColor',[0 0 0], ...
    'FontName','Consolas', ...
    'FontSize', fontsize3, ...
    'Callback',@ret.onAnyInputChanged);

end